# Default image (https://hub.docker.com/_/ubuntu/)
image: ubuntu:20.04

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -yqq
  - apt-get install -yqq openjdk-17-jdk ant junit5

# Build
build_game:
  stage: build
  script:
    - ant compile
    - ant jar

# Test
test_model:
  stage: test
  script:
    - >
      ant test -Dlibs.junit_5.classpath=/usr/share/java/junit-jupiter-api.jar:/usr/share/java/junit-jupiter-engine.jar:/usr/share/java/junit-jupiter-params.jar:/usr/share/java/junit-platform-commons.jar:/usr/share/java/junit-platform-console.jar
      -Dlibs.hamcrest.classpath=/usr/share/java/hamcrest-core.jar

# Documentation
pages:
  stage: deploy
  script:
    - ant javadoc
    - cp -r dist/javadoc/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master

