# Default image (https://hub.docker.com/_/ubuntu/)
image: ubuntu:20.04

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -yqq
  - apt-get install -yqq openjdk-17-jdk ant junit5 curl

# Build
build_game:
  stage: build
  script:
    - ant compile
    - ant jar

# Test
test_model:
  stage: test
  variables:
    junit_platform_version: 1.9.3
    ant_version: 1.10.13
    ant_folder: apache-ant-${ant_version}
    ant_archive: ${ant_folder}-bin.tar.gz
  script:
    # Based on: https://github.com/junit-team/junit5-samples/tree/main/junit5-jupiter-starter-ant
    # Load and extract Apache Ant.
    - curl --remote-name "https://archive.apache.org/dist/ant/binaries/${ant_archive}"
    - tar --extract -z --exclude "${ant_folder}/manual" --file "${ant_archive}"
    # Load and store junit-platform-console-standalone jar into ${ANT_HOME}/lib.
    - cd "${ant_folder}/lib"
    - curl --remote-name  "https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/${junit_platform_version}/junit-platform-console-standalone-${junit_platform_version}.jar"
    - cd $CI_PROJECT_DIR
    # Finally, let Ant do its work...
    - ANT_HOME=${ant_folder} "./${ant_folder}/bin/ant" -buildfile build-custom.xml test

# Documentation
pages:
  stage: deploy
  script:
    - ant javadoc
    - cp -r dist/javadoc/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - master

